### ISSUE TITLE
Add a More Information link

### ISSUE THREAD

**Issue by yannduran** [samartzidis/MSBuildTargetsVsExtension#2]
## What's The Problem?

As I was going through the extensions that I have installed, I saw yours in the list. I wanted to remind myself why I'd installed your extension, but there was no '_More Information_' link to click on.

Instead I had to switch to a browser and type in a search.

#### This is your extension (with no link):

![image](https://user-images.githubusercontent.com/2031126/33748022-4fb36436-dc1a-11e7-8fed-9d1f9ef9573e.png)

#### This is another extension (that has a link):

![image](https://user-images.githubusercontent.com/2031126/33748064-92de933e-dc1a-11e7-8427-fdef2ee51f09.png)

#### In the vsix manifest (on the metadata tab):

![image](https://user-images.githubusercontent.com/2031126/33748145-fac02d28-dc1a-11e7-8f69-99b02f4ca2d8.png)

####  In the '_More Info URL_' field, put a link:
- to the extension in the MarketPlace 
- or to the GitHub repo
- or to any other web page that has more information about the extension

**Comment by samartzidis** [comment]
Thanks for commenting on this and for also suggesting the fix. I will have
that changed in the next release.

**Comment by yannduran** [comment]
You're welcome Geroge! And thanks for super-fast response.

I realised later that I should have saved you the trouble and created a pull request. Sorry about that.
